export let ShopText = [
    {alias: 'shop', en: 'Online shop', de: 'Online-Shop'},
    {alias: 'price', en: 'Price', de: 'Preis'},
    {alias: 'tip', en: 'Tip', de: 'Trinkgeld'},
    {alias: 'cash', en: 'Cash', de: 'Kasse'},
    {alias: 'sale', en: 'Sale', de: 'Verkauf'},
    {alias: 'sales', en: 'Sales', de: 'Verkäufe'},
    {alias: 'amount', en: 'Amount', de: 'Menge'},
    {alias: 'itemNumber', en: 'Item number', de: 'Artikelnummer'},
    {alias: 'imageId', en: 'Image', de: 'Bild'},
    {alias: 'manufacturer', en: 'Manufacturer', de: 'Hersteller'},
    {alias: 'manufacturerId', en: 'Manufacturer', de: 'Hersteller'},
    {alias: 'manufacturers', en: 'Manufacturers', de: 'Hersteller'},
    {alias: 'manufacturerIds', en: 'Manufacturers', de: 'Hersteller'},
    {alias: 'currency', en: 'Currency', de: 'Währung'},
    {alias: 'currencyId', en: 'Currency', de: 'Währung'},
    {alias: 'currencies', en: 'Currencies', de: 'Währungen'},
    {alias: 'currencyIds', en: 'Currencies', de: 'Währungen'},
    {alias: 'category', en: 'Category', de: 'Kategorie'},
    {alias: 'categoryId', en: 'Category', de: 'Kategorie'},
    {alias: 'categories', en: 'Categories', de: 'Kategorien'},
    {alias: 'categoryIds', en: 'Categories', de: 'Kategorien'},
    {alias: 'group', en: 'Group', de: 'Gruppe'},
    {alias: 'groupId', en: 'Group', de: 'Gruppe'},
    {alias: 'groups', en: 'Groups', de: 'Gruppen'},
    {alias: 'groupIds', en: 'Groups', de: 'Gruppen'},
    {alias: 'tax', en: 'Tax rate', de: 'Steuersatz'},
    {alias: 'taxId', en: 'Tax rate', de: 'Steuersatz'},
    {alias: 'taxIds', en: 'Tax rates', de: 'Steuersätze'},
    {alias: 'typeId', en: 'Type', de: 'Typ'},
    {alias: 'typeIds', en: 'Types', de: 'Typen'},
    {alias: 'discount', en: 'Discount', de: 'Rabatt'},
    {alias: 'discountId', en: 'Discount', de: 'Rabatt'},
    {alias: 'discounts', en: 'Discounts', de: 'Rabatte'},
    {alias: 'discountIds', en: 'Discounts', de: 'Rabatte'},
    {alias: 'payment', en: 'Payment', de: 'Bezahlverfahren'},
    {alias: 'paymentId', en: 'Payment', de: 'Bezahlverfahren'},
    {alias: 'payments', en: 'Payments', de: 'Bezahlverfahren'},
    {alias: 'paymentIds', en: 'Payments', de: 'Bezahlverfahren'},
    {alias: 'shipping', en: 'Shipping', de: 'Versandart'},
    {alias: 'shippingId', en: 'Shipping', de: 'Versandart'},
    {alias: 'shippingIds', en: 'Shippings', de: 'Versandart'},
    {alias: 'shipping_types', en: 'Shipping types', de: 'Versandarten'},
    {alias: 'all_categories', en: 'All categories', de: 'Alle Kategorien'},
    {alias: 'all_groups', en: 'All Groups', de: 'Alle Gruppen'},
    {alias: 'product', en: 'Product', de: 'Produkt'},
    {alias: 'individual-product', en: 'Custom', de: 'Benutzerdefiniert'},
    {alias: 'select_products', en: 'Select products', de: 'Produkte auswählen'},
    {alias: 'product_type', en: 'Type', de: 'Typ'},
    {alias: 'product_types', en: 'Types', de: 'Typen'},
    {alias: 'product_group', en: 'Group', de: 'Gruppe'},
    {alias: 'product_groups', en: 'Groups', de: 'Gruppen'},
    {alias: 'product_category', en: 'Category', de: 'Kategorie'},
    {alias: 'product_categories', en: 'Categories', de: 'Kategorien'},
    {
        alias: 'no_products_available_for_selection',
        en: 'No products available for this selection',
        de: 'Für diese Auswahl sind keine Produkte vorhanden'
    },
    {alias: 'checkout', en: 'Checkout', de: 'Zur Kasse'},
    {alias: 'pay', en: 'Pay', de: 'Bezahlen'},
    {alias: 'checkout_overview', en: 'Sales', de: 'Verkäufe'},
    {alias: 'checkout_info', en: 'Checkout Infos', de: 'Kassen-Infos'},
    {alias: 'all', en: 'All', de: 'Alle'},
    {alias: 'all_types', en: 'All types', de: 'Alle Arten'},
    {alias: 'date', en: 'Date', de: 'Datum'},
    {alias: 'total', en: 'Total', de: 'Gesamt'},
    {alias: 'seller', en: 'Seller', de: 'Verkäufer'},
    {alias: 'single_price', en: 'Single price', de: 'Einzelpreis'},
    {alias: 'customer', en: 'Customer', de: 'Kunde'},
    {alias: 'customerId', en: 'Customer', de: 'Kunde'},
    {alias: 'customers', en: 'Customers', de: 'Kunden'},
    {alias: 'customerIds', en: 'Customers', de: 'Kunden'},
    {alias: 'employee', en: 'Employee', de: 'Mitarbeiter'},
    {alias: 'employeeId', en: 'Employee', de: 'Mitarbeiter'},
    {alias: 'employees', en: 'Employees', de: 'Mitarbeiter'},
    {alias: 'employeeIds', en: 'Employees', de: 'Mitarbeiter'},
    {alias: 'back_to_cash_register', en: 'Back to cash register', de: 'Zurück zur Kasse'},
    {alias: 'cashRegister', en: 'Cash register', de: 'Kasse'},
    {alias: 'onlineShop', en: 'Online shop', de: 'Online-Shop'},
    {alias: 'print_receipt', en: 'receipt', de: 'Kassenbon'},
    {alias: 'show_products', en: 'Show product', de: 'Produkt anzeigen'},
    {alias: 'product_configuration', en: 'Product config', de: 'Produkt-Einstellungen'},
    {alias: 'custom_product', en: 'Custom', de: 'Benutzerdefiniert'},
    {
        alias: 'no_sells_in_period',
        en: 'No sales were made during this period',
        de: 'In diesem Zeitraum wurden keine Verkäufe getätigt'
    },
    {alias: 'no_products_in_cash_register', en: 'No products in cash register', de: 'Keine Produkte in der Kasse'},
    {alias: 'all_seller', en: 'All seller', de: 'Alle Verkäufer'},
    {alias: 'add_new_user', en: 'Add new user', de: 'Neuen Benutzer anlegen'},
    {alias: 'purchase', en: 'Purchase', de: 'Einkauf'},
    {alias: 'purchases', en: 'Purchases', de: 'Einkäufe'},
    {alias: 'no_purchases', en: 'No purchases available', de: 'Keine Einkäufe vorhanden'},
    {alias: 'no_payments', en: 'No payment methods available', de: 'Keine Zahlungsarten vorhanden'},
    {alias: 'no_currencies', en: 'No currencies available', de: 'Keine Währung vorhanden'},
    {alias: 'no_taxes', en: 'No tax rates available', de: 'Keine Steuersätze vorhanden'},
    {alias: 'no_shipping', en: 'No shipping type available', de: 'Keine Versandart vorhanden'},
    {alias: 'no_manufacturers', en: 'No manufacturer available', de: 'Keine Hersteller vorhanden'},
    {alias: 'no_discounts', en: 'No discounts available', de: 'Keine Rabatte vorhanden'},
    {alias: 'new_payments', en: 'New payment method', de: 'Neue Zahlungsart'},
    {alias: 'new_currencies', en: 'New currency', de: 'Neue Währung'},
    {alias: 'new_taxes', en: 'New tax rate', de: 'Neuen Steuersatz'},
    {alias: 'new_shipping', en: 'New shipping type', de: 'Neue Versandart'},
    {alias: 'new_manufacturers', en: 'New manufacturer', de: 'Neuen Hersteller'},
    {alias: 'new_discounts', en: 'New discount', de: 'Neuen Rabatt'},
    {alias: 'thank_you_for_shopping', en: 'Thank you for shopping', de: 'Vielen Dank für den Einkauf'},
    {alias: 'your_products', en: 'Your products', de: 'Ihre Produkte'},
    {alias: 'see_you_soon', en: 'See you soon', de: 'Bis zum nächsten mal'},
    {alias: 'thank_you', en: 'Thank you!', de: 'Vielen Dank!'},
    {alias: 'today', en: 'Today', de: 'Heute'},
    {alias: 'no_product_groups', en: 'No group available', de: 'Keine Gruppe verfügbar'},
    {alias: 'no_product_categories', en: 'No category available', de: 'Keine Kategorie verfügbar'},
    {alias: 'no_product_types', en: 'No type available', de: 'Kein Produkttyp verfügbar'},
    {alias: 'new_product_group', en: 'New group', de: 'Neue Gruppe'},
    {alias: 'new_product_category', en: 'New category', de: 'Neue Kategorie'},
    {alias: 'new_product_type', en: 'New type', de: 'Neuer Produkttyp'},
    {alias: 'new_product', en: 'New product', de: 'Neues Produkt'},
    {alias: 'new_payment', en: 'New payment', de: 'Neues Bezahlverfahren'},
    {alias: 'new_currency', en: 'New currency', de: 'Neue Währung'},
    {alias: 'new_tax', en: 'New tax rate', de: 'Neuen Steuersatz'},
    {alias: 'new_manufacturer', en: 'New manufacturer', de: 'Neuen Hersteller'},
    {alias: 'new_discount', en: 'New discount', de: 'Neuen Rabatt'},
    {alias: 'no_payment_available', en: 'No payment method available', de: 'Kein Bezahlverfahren verfügbar'},
    {alias: 'configuration_page', en: 'Go to configuration', de: 'Zur Konfiguration'},
    {alias: 'list', en: 'List', de: 'Liste'},
    {alias: 'cash', en: 'Cash', de: 'Bar'},
    {alias: 'card', en: 'Card', de: 'Karte'},
    {alias: 'online', en: 'Online', de: 'Online'},
    {alias: 'device', en: 'Device', de: 'Gerät'},
];
