export let ShopText = [
    {alias: 'shop', en: 'Online shop', de: 'Online-Shop'},
    {alias: 'cash', en: 'Cash', de: 'Kasse'},
    {alias: 'itemNumber', en: 'Item number', de: 'Artikelnummer'},
    {alias: 'imageId', en: 'Image', de: 'Bild'},
    {alias: 'manufacturer', en: 'Manufacturer', de: 'Hersteller'},
    {alias: 'manufacturerId', en: 'Manufacturer', de: 'Hersteller'},
    {alias: 'manufacturers', en: 'Manufacturers', de: 'Hersteller'},
    {alias: 'manufacturerIds', en: 'Manufacturers', de: 'Hersteller'},
    {alias: 'currency', en: 'Currency', de: 'Währung'},
    {alias: 'currencyId', en: 'Currency', de: 'Währung'},
    {alias: 'currencies', en: 'Currencies', de: 'Währungen'},
    {alias: 'currencyIds', en: 'Currencies', de: 'Währungen'},
    {alias: 'category', en: 'Category', de: 'Kategorie'},
    {alias: 'categoryId', en: 'Category', de: 'Kategorie'},
    {alias: 'categories', en: 'Categories', de: 'Kategorien'},
    {alias: 'categoryIds', en: 'Categories', de: 'Kategorien'},
    {alias: 'group', en: 'Group', de: 'Gruppe'},
    {alias: 'groupId', en: 'Group', de: 'Gruppe'},
    {alias: 'groups', en: 'Groups', de: 'Gruppen'},
    {alias: 'groupIds', en: 'Groups', de: 'Gruppen'},
    {alias: 'tax', en: 'Tax', de: 'Steuern'},
    {alias: 'taxId', en: 'Tax', de: 'Steuern'},
    {alias: 'discount', en: 'Discount', de: 'Rabatt'},
    {alias: 'discountId', en: 'Discount', de: 'Rabatt'},
    {alias: 'discounts', en: 'Discounts', de: 'Rabatte'},
    {alias: 'discountIds', en: 'Discounts', de: 'Rabatte'},
    {alias: 'shipping', en: 'Shipping', de: 'Lieferung'},
    {alias: 'shippingId', en: 'Shipping', de: 'Lieferung'},
    {alias: 'shippingIds', en: 'Shippings', de: 'Lieferungen'},
    {alias: 'all_categories', en: 'All categories', de: 'Alle Kategorien'},
    {alias: 'all_groups', en: 'All Groups', de: 'Alle Gruppen'},
    {alias: 'product_groups', en: 'Product groups', de: 'Produktgruppen'},
    {alias: 'product_categories', en: 'Product categories', de: 'Produktkategorien'},
    {
        alias: 'no_products_available_for_selection',
        en: 'No products available for this selection',
        de: 'Für diese Auswahl sind keine Produkte vorhanden'
    },
];
