export let ShopText = [
    {alias: 'shop', en: 'Online shop', de: 'Online-Shop'},
    {alias: 'cash', en: 'Cash', de: 'Kasse'},
    {alias: 'sale', en: 'Sale', de: 'Verkauf'},
    {alias: 'sales', en: 'Sales', de: 'Verkäufe'},
    {alias: 'amount', en: 'Amount', de: 'Menge'},
    {alias: 'itemNumber', en: 'Item number', de: 'Artikelnummer'},
    {alias: 'imageId', en: 'Image', de: 'Bild'},
    {alias: 'manufacturer', en: 'Manufacturer', de: 'Hersteller'},
    {alias: 'manufacturerId', en: 'Manufacturer', de: 'Hersteller'},
    {alias: 'manufacturers', en: 'Manufacturers', de: 'Hersteller'},
    {alias: 'manufacturerIds', en: 'Manufacturers', de: 'Hersteller'},
    {alias: 'currency', en: 'Currency', de: 'Währung'},
    {alias: 'currencyId', en: 'Currency', de: 'Währung'},
    {alias: 'currencies', en: 'Currencies', de: 'Währungen'},
    {alias: 'currencyIds', en: 'Currencies', de: 'Währungen'},
    {alias: 'category', en: 'Category', de: 'Kategorie'},
    {alias: 'categoryId', en: 'Category', de: 'Kategorie'},
    {alias: 'categories', en: 'Categories', de: 'Kategorien'},
    {alias: 'categoryIds', en: 'Categories', de: 'Kategorien'},
    {alias: 'group', en: 'Group', de: 'Gruppe'},
    {alias: 'groupId', en: 'Group', de: 'Gruppe'},
    {alias: 'groups', en: 'Groups', de: 'Gruppen'},
    {alias: 'groupIds', en: 'Groups', de: 'Gruppen'},
    {alias: 'tax', en: 'Tax', de: 'Steuern'},
    {alias: 'taxId', en: 'Tax', de: 'Steuern'},
    {alias: 'taxIds', en: 'Taxes', de: 'Steuern'},
    {alias: 'typeId', en: 'Type', de: 'Typ'},
    {alias: 'typeIds', en: 'Types', de: 'Typen'},
    {alias: 'discount', en: 'Discount', de: 'Rabatt'},
    {alias: 'discountId', en: 'Discount', de: 'Rabatt'},
    {alias: 'discounts', en: 'Discounts', de: 'Rabatte'},
    {alias: 'discountIds', en: 'Discounts', de: 'Rabatte'},
    {alias: 'payment', en: 'Payment', de: 'Zahulungsart'},
    {alias: 'paymentId', en: 'Payment', de: 'Zahulungsart'},
    {alias: 'payments', en: 'Payments', de: 'Zahulungsarten'},
    {alias: 'paymentIds', en: 'Payments', de: 'Zahulungsarten'},
    {alias: 'shipping', en: 'Shipping', de: 'Lieferung'},
    {alias: 'shippingId', en: 'Shipping', de: 'Lieferung'},
    {alias: 'shippingIds', en: 'Shippings', de: 'Lieferungen'},
    {alias: 'shipping_types', en: 'Shipping types', de: 'Versandarten'},
    {alias: 'all_categories', en: 'All categories', de: 'Alle Kategorien'},
    {alias: 'all_groups', en: 'All Groups', de: 'Alle Gruppen'},
    {alias: 'select_products', en: 'Select products', de: 'Produkte auswählen'},
    {alias: 'product_type', en: 'Product type', de: 'Produktart'},
    {alias: 'product_types', en: 'Product types', de: 'Produktarten'},
    {alias: 'product_group', en: 'Product group', de: 'Produktgruppe'},
    {alias: 'product_groups', en: 'Product groups', de: 'Produktgruppen'},
    {alias: 'product_category', en: 'Product category', de: 'Produktkategorie'},
    {alias: 'product_categories', en: 'Product categories', de: 'Produktkategorien'},
    {
        alias: 'no_products_available_for_selection',
        en: 'No products available for this selection',
        de: 'Für diese Auswahl sind keine Produkte vorhanden'
    },
    {alias: 'checkout', en: 'Checkout', de: 'Zur Kasse'},
    {alias: 'pay', en: 'Pay', de: 'Bezahlen'},
    {alias: 'checkout_overview', en: 'Sales', de: 'Verkäufe'},
    {alias: 'checkout_info', en: 'Checkout Infos', de: 'Kassen-Infos'},
    {alias: 'all', en: 'All', de: 'Alle'},
    {alias: 'all_types', en: 'All types', de: 'Alle Arten'},
    {alias: 'date', en: 'Date', de: 'Datum'},
    {alias: 'total', en: 'Total', de: 'Gesamt'},
    {alias: 'seller', en: 'Seller', de: 'Verkäufer'},
    {alias: 'single_price', en: 'Single price', de: 'Einzelpreis'},
    {alias: 'customer', en: 'Customer', de: 'Kunde'},
    {alias: 'back_to_cash_register', en: 'Back to cash register', de: 'Zurück zur Kasse'},
    {alias: 'cashRegister', en: 'Cash register', de: 'Kasse'},
    {alias: 'onlineShop', en: 'Online shop', de: 'Online-Shop'},
    {alias: 'print_receipt', en: 'receipt', de: 'Kassenbon'},
    {alias: 'show_products', en: 'Show product', de: 'Produkt anzeigen'},
    {alias: 'product_configuration' , en: 'Product config', de: 'Produkt-Einstellungen'},
    {alias: 'custom_product', en: 'Custom', de: 'Benutzerdefiniert'},
    {alias: 'no_sells_in_period', en: 'No sales were made during this period', de: 'In diesem Zeitraum wurden keine Verkäufe getätigt'},
    {alias: 'no_products_in_cash_register', en: 'No products in cash register', de: 'Keine Produkte in der Kasse'},
    {alias: 'all_seller', en: 'All seller', de: 'Alle Verkäufer'},
    {alias: 'add_new_user', en: 'Add new user', de: 'Neuen Benutzer anlegen'},
    {alias: 'purchase', en: 'Purchase', de: 'Einkauf'},
    {alias: 'thank_you_for_shopping', en:'Thank you for shopping', de:'Vielen Dank für den Einkauf'},
    {alias: 'your_products', en:'Your products', de:'Ihre Produkte'},
    {alias: 'see_you_soon', en:'See you soon', de:'Bis zum nächsten mal'},
    {alias: 'thank_you', en:'Thank you!', de:'Vielen Dank!'},
    {alias: 'today', en:'Today', de:'Heute'}
];
